name: x-sum-type-boilerplate
version: "0.1.4"
maintainer: David Reaver, xieyuschen
author: David Reaver, xieyuschen
synopsis: (Forked) Library for reducing the boilerplate involved with sum types
description: (Forked) Library for reducing the boilerplate involved in creating and manipulating sum types
stability: experimental
category: Types,TH
license: MIT
license-file: LICENSE.md

github: xieyuschen/x-sum-type-boilerplate

extra-source-files:
  - CHANGELOG.md
  - README.md

dependencies:
  - base >= 4.9 && < 5

  - template-haskell

library:
  source-dirs:
    - library
  ghc-options: -Wall

tests:
  spec:
    main: Spec.hs
    ghc-options: -Wall
    source-dirs:
      - tests
    dependencies:
      - hspec
      - x-sum-type-boilerplate
